#!/bin/bash

sudo cp pirhdmi /usr/local/bin
sudo chmod +x /usr/local/bin/pirhdmi
sudo cp pirhdmi.service /lib/systemd/system
sudo chmod 644 /lib/systemd/system/pirhdmi.service
sudo systemctl daemon-reload
sudo systemctl enable pirhdmi.service
sudo systemctl start pirhdmi.service

