#!/usr/bin/env python3

import subprocess
import threading
from gpiozero import MotionSensor
from signal import pause
pir = MotionSensor(4)
TVSERVICE='/usr/bin/tvservice'
FGCONSOLE='/bin/fgconsole'
CHVT='/bin/chvt'
ON_TIME=30.0

def is_off():
    status = subprocess.check_output([TVSERVICE, "-s"]).decode("utf-8")
    if "TV is off" in status:
        return True
    else:
        return False

def fgconsole():
    return subprocess.check_output([FGCONSOLE]).decode("utf-8").rstrip()

def hdmi_off():
    subprocess.run([TVSERVICE, '-o'])

def start_off_timer():
    global timer
    timer = threading.Timer(ON_TIME, lambda: hdmi_off())
    timer.start()

def restart_off_timer():
    global timer
    timer.cancel()
    start_off_timer()

def hdmi_on():
    if is_off():
        subprocess.run([TVSERVICE, '-p'])
        curr_vt=fgconsole()
        if curr_vt == '1':
            subprocess.run([CHVT, '2'])
            subprocess.run([CHVT, '1'])
        else:
            subprocess.run([CHVT, '1'])
            subprocess.run([CHVT, curr_vt])
        start_off_timer()
    else:
        restart_off_timer()

pir.when_motion = lambda : hdmi_on()

hdmi_off()
pause()

